In [1]:
import numpy as np

## How to take the k biggest values along a given axis for a given matrix:

In [2]:
x = np.random.rand(5, 5)
print(x)
a = np.argsort(x, axis=1)
# argsort gives ascending order so we have to reverse the order
a = a[:, -1::-1]
print(a)
# a contains only the indices along the second axis (the columns) but for integer indexing we also need the row indices:
# they will be broadcasted so we need it to be 2D array
rows = np.arange(5)[:, np.newaxis]
print(rows)
print(x[rows, a[:, 0:3]])

[[0.60080737 0.67869159 0.2950931  0.22690127 0.43422898]
 [0.82156904 0.72417623 0.60568798 0.46421807 0.78133806]
 [0.44970497 0.76147525 0.64039773 0.02456953 0.30827886]
 [0.56624744 0.77421173 0.7109107  0.19469638 0.00313829]
 [0.75471545 0.90058493 0.74241208 0.88063427 0.55420083]]
[[1 0 4 2 3]
 [0 4 1 2 3]
 [1 2 0 4 3]
 [1 2 0 3 4]
 [1 3 0 2 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0.67869159 0.60080737 0.43422898]
 [0.82156904 0.78133806 0.72417623]
 [0.76147525 0.64039773 0.44970497]
 [0.77421173 0.7109107  0.56624744]
 [0.90058493 0.88063427 0.75471545]]
