In [1]:
import numpy as np

## How to take the k biggest values along a given axis for a given matrix:

In [28]:
x = np.random.rand(5, 5)
print(x)
a = np.argsort(x, axis=1)
# argsort gives ascending order so we have to reverse the order
a = a[:, -1::-1]
print(a)
# a contains only the indices along the second axis (the columns) but for integer indexing we also need the row indices:
# they will be broadcasted so we need it to be 2D array
rows = np.arange(5)[:, np.newaxis]
print(rows)
print(x[rows, a[:, 0:3]])

[[ 0.27659282  0.22354457  0.52403525  0.04163469  0.24928904]
 [ 0.3367763   0.17199404  0.01614703  0.19170751  0.30358093]
 [ 0.01378044  0.00509645  0.83467048  0.66864518  0.51291153]
 [ 0.41099473  0.55436658  0.6980684   0.1762442   0.96674766]
 [ 0.55626625  0.99798986  0.03897142  0.46527371  0.19898507]]
[[2 0 4 1 3]
 [0 4 3 1 2]
 [2 3 4 0 1]
 [4 2 1 0 3]
 [1 0 3 4 2]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0.52403525  0.27659282  0.24928904]
 [ 0.3367763   0.30358093  0.19170751]
 [ 0.83467048  0.66864518  0.51291153]
 [ 0.96674766  0.6980684   0.55436658]
 [ 0.99798986  0.55626625  0.46527371]]
